# Generated by Django 5.2.5 on 2025-09-03 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="booking_hot_name_6696b5_idx"),
                    models.Index(fields=["city"], name="booking_hot_city_ac6ca1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single"),
                            ("DOUBLE", "Double"),
                            ("SUITE", "Suite"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                ("capacity", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="booking.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guest_name", models.CharField(max_length=100)),
                ("guest_email", models.EmailField(max_length=254)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.room",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type"], name="booking_roo_room_ty_81d7c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_available"], name="booking_roo_is_avai_2c7faa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hotel", "room_number")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_date", "check_out_date"],
                name="booking_boo_check_i_89e08a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["is_cancelled"], name="booking_boo_is_canc_989417_idx"
            ),
        ),
    ]
