# Generated by Django 5.2.5 on 2025-09-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="available_from",
            field=models.DateField(
                blank=True, help_text="Date from which room is available", null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="available_to",
            field=models.DateField(
                blank=True, help_text="Date until which room is available", null=True
            ),
        ),
    ]
